### ISSUE TITLE
Complete the clock interface with ..

### ISSUE THREAD

**Issue by hhugo** [mirage/mirage-clock#1]
`val gettimeofday : unit -> float`
`val localtime : float -> tm`
`val mktime : tm -> float * tm`

is there any issue with xen ?

**Comment by djs55** [comment]
The mirage equivalent of 'gettimeofday' is:

```
external time : unit -> float = "unix_gettimeofday"
```

The hypervisor will tell the VM the time in UTC, but the concept of "local
time" is local to the VM (since each VM may be in a different timezone). I
think local time can be quite complicated, especially when countries decide
to change the day they switch to and from daylight savings time. Personally
I try to avoid this as much as possible by (for example) always logging
everything in UTC :-)

Perhaps mirage needs a 'calendar' interface as well as a 'clock'?

On Thu, Jan 16, 2014 at 8:09 PM, hhugo notifications@github.com wrote:

> val gettimeofday : unit -> float
> val localtime : float -> tm
> val mktime : tm -> float \* tm
> 
> is there any issue with xen ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mirage/mirage-clock/issues/1
> .

## 

Dave Scott

**Comment by hhugo** [comment]
I propose to have localtime returning the UTC (no daylight saving) and document the behavior
the localtime/timezone/daylight_saving feature can be done later on.
( https://github.com/eggert/tz | ftp://ftp.iana.org/tz/tz-link.html )

I'm more interested in `mktime`
I use this signature in a date/duration library there https://github.com/hhugo/odate/blob/master/src/oDate.mli#L47

**Comment by avsm** [comment]
I do have strongly prefer to have Clock be just a timesource, and have a Timezone, Calendar and other module to handle the localization aspects.  The reason is that Clock is essential for pretty much every other component, and forcing this minimal signature to include localtime would add a dependency on every backend...(such as the kernel FreeBSD one, for example)

**Comment by dbuenzli** [comment]
Based on my modest investigations in the fascinating subject of civilian time keeping, if clock is supposed to provide calendar time, I think the right interface would be to provide the following two functions (that's what I have designed for bos, see [here](http://erratique.ch/software/bos/doc/Bos_unix.OS.Time.html) and [here](http://erratique.ch/software/bos/doc/Bos.OS.Time.html)): 

``` ocaml
type posix_s = float (* POSIX time in seconds *)
type tz_offset_min = int (* time zone offset to UTC in minutes *) 

val now_s : unit -> posix_s
val current_tz_offset_min  : unit -> tz_offset_min
```

this is all what is needed to be able to format [RFC 3339](http://tools.ietf.org/html/rfc3339) time stamps.

@djs55 logging everything in UTC is not very user friendly, I suspect it works for you because you live in the UK... If you have the offset in minutes to UTC, RFC3339 provides an excellent solution to this problem without needing these insane (and ambiguous) tz denomination/databases. 

Also a slight (non-standard) modification of RFC3339 --- replace the  `T` by a space and introduce a space between time and time zone offset: 

```
2015-03-11T23:33:22+0100
2015-03-11 23:33:22 +0100
```

make very human readable timestamps for logging. These stamps are in your local time and unambiguously define their relationship to UTC without needing tz databases and are easy to convert back to POSIX time; FWIW that's the default timestamp formatting of `git log`.

For reference [here](https://github.com/dbuenzli/bos/blob/351205f94654210b1701d59b2186ad040d3ffaf1/src-unix/bos_unix.ml#L123-L133)'s how you can derive `current_tz_offset_min` function from `gmtime` and `localtime`. 

The advantage of this interface is that a clock is only required to provide POSIX time and, if it strives to be user friendly, a time zone offset in minutes; it can always return 0 if it doesn't want to be so. Notably it doesn't need to perform any form of calendar calculation (as @talex5 suggested [here](https://github.com/mirage/mirage/issues/333#issuecomment-65376727)).

Using these two bits of information and pure OCaml code like provided in PR #2, RFC 3339 formatting (standard and human) is [one simple function](https://github.com/dbuenzli/bos/blob/351205f94654210b1701d59b2186ad040d3ffaf1/src-unix/bos_unix.ml#L135-L148) away. I'd even suggest that we provide a backend independent package in mirage-clock that provides functions based on the code in PR #2 do so. 

If we agree on that should that maybe be part of the changes for MirageOS 3.0 ?

**Comment by mor1** [comment]
That seems generally correct to me, though I would usually speak up for logging in UTC only as well, with an explicit offset to localtime, not some kind of indirection to a confused TZ database. Being able to easily merge log files when they're (eg) collected in different timezones is a nice thing to be able to do. 

But really, anything that's well-defined, stable and amenable via easily available APIs to sorting/printing readably/comparing/etc would do IMO.

Apropos this discussion, though somewhat off topic, I found the following interesting/amusing reads concerning this sort of thing:
- http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time
- http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time
- http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
- https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/
- http://wiesmann.codiferes.net/wordpress/?p=15187&lang=en (falsehoods about geography)

**Comment by dbuenzli** [comment]
> That seems generally correct to me, though I would usually speak up for logging in UTC only as well, with an explicit offset to localtime, not some kind of indirection to a confused TZ database. Being able to easily merge log files when they're (eg) collected in different timezones is a nice thing to be able to do.

That's exactly what any RFC 3339 timestamp gives you; once you have converted the time stamp back to POSIX time for comparing. Convertion for which you won't need a tz database. For the end-user having a time to which he can relate directly is much more usable so I wouldn't advise to log in UTC but in RFC 3339 time stamps with the timezone offset provided by the OS. But I'd say this is highly dependent on your application and setting; for example if you want to be able to merge logs using `cat` and `sort` then you should effectively log stamps with a single, fixed, time zone offset; binary sorting ASCII or UTF-8 encoded RFC 3339 timestamps that belong to the same time zone, yields [timeline order](http://tools.ietf.org/html/rfc3339#section-5.1).

**Comment by talex5** [comment]
This interface looks racey to me:

``` ocaml
val now_s : unit -> posix_s
val current_tz_offset_min  : unit -> tz_offset_min
```

The offset may change between calling the two functions (e.g. at DST switch-over).

It would probably be better to represent times as something like:

``` ocaml
type timestamp = {
  utc : float;                (* Seconds since Unix epoch *)
  offset_to_local_tz : int;   (* Seconds * )
}
```

I think it's slightly better to store the time in UTC and the offet to local time (rather than storing local time and offset to UTC) because:
- Polymorphic compare will work correctly.
- Bulk processing usually wants UTC, whereas conversions to local time for display are roughly limited to the speed at which a human can read.

I'd also suggest using seconds for the offset. Using different units for the two fields seems pointless.

**Comment by dbuenzli** [comment]
> This interface looks racey to me:

It's not, `now_s` doesn't return local time, it returns POSIX time, POSIX time is always in UTC. I'd rather not have the timezone stuff in raw timestamps. 

> I'd also suggest using seconds for the offset. Using different units for the two fields seems pointless.

Agreed, also slightly less error prone (though since you have to convert to add to a posix timestamp you have to think). So maybe this is better:

``` ocaml
type posix_s = float (* POSIX time in seconds *)
type tz_offset_s = float (* time zone offset to UTC in seconds *) 

val now_s : unit -> posix_s
val current_tz_offset_s  : unit -> tz_offset_s
```

**Comment by dbuenzli** [comment]
> It's not, now_s doesn't return local time, it returns POSIX time, POSIX time is always in UTC. I'd rather not have the timezone stuff in raw timestamps.

But indeed if you'd really like to know the current local time when you call `now_s` you can't. Personally I don't really care about that and I don't know if there are reasons to (I tend to see the time zone stuff as both metadata about time and a rendering issue). If people think it is important I'd rather have a third function that tuples the stamp with the tz_offset.

``` ocaml
val now_and_tz_offset_s : unit -> posix_s * tz_offset_s
```

**Comment by talex5** [comment]
I see, so `current_tz_offset_s` just suggests the local time-zone for a time source.

Seems reasonable. Although perhaps converting times for display should be a property of the logger rather than the time-source? Of course, that would require getting a proper logging framework for Mirage, which is another problem...

**Comment by dbuenzli** [comment]
> I see, so current_tz_offset_s just suggests the local time-zone for a time source.

Yes.

> Although perhaps converting times for display should be a property of the logger rather than the time-source?

Yes that's what this proposal enables. Once you have these two bits of information (posix time and utc offset) it becomes trivial to render local time, see e.g. [this function](https://github.com/dbuenzli/bos/blob/master/src-unix/bos_unix.ml#L148-L161). It uses Unix's `gmtime`, but it could use the pure OCaml code of #2. 

Also here's a way to implement [`current_tz_offset_s`](https://github.com/dbuenzli/bos/blob/master/src-unix/bos_unix.ml#L136-L146), using `Unix.{gmtime,localtime}`.

**Comment by yomimono** [comment]
I believe the issues raised here are addressed by the creation of `MCLOCK` and `PCLOCK`, combined with [ptime](http://erratique.ch/software/ptime).  Please feel free to open a new issue if something is still missing.
