### ISSUE TITLE
integer overflow on 32bits platform within posix_clock_gettime_s_ns

### ISSUE THREAD

**Issue by sevenEng** [mirage/mirage-clock#17]
hit this bug while testing some mirage application on cubietruck

i think the problem comes from this [c stub function](https://github.com/mirage/mirage-clock/blob/master/unix/clock_stubs.c#L85)

which, on 32bits platform, returns negative values, and causes Ptime.v to raise an [exception](https://github.com/dbuenzli/ptime/blob/8267c82e34edf10659617b1a917df01135fb06cd/src/ptime.ml#L311) when called upon from mirage-logs [report](https://github.com/mirage/mirage-logs/blob/master/lib/mirage_logs.ml#L89]) function

as the logs package is widely used among various mirage libraries, I think this bug would effectively prevent any application from working properly on 32bits platform when targeting unix

**Comment by dbuenzli** [comment]
Current posix time in seconds overflows the maximal value of OCaml `int` (2 ^ 30 - 1) on 32-bit platforms since 2004 so the conversion to `int` made to return to OCaml in the C function you mention effectively results in a negative number on 32-bit platforms.

[`Ptime_clock`](http://erratique.ch/software/ptime/doc/Ptime_clock.html) on Unix side-steps the issue by doing the conversion to the ptime representation on [the C side](https://github.com/dbuenzli/ptime/blob/8267c82e34edf10659617b1a917df01135fb06cd/src-os/ptime_clock_stubs.c#L42-L73).  Note that you should be able to use the module `Ptime_clock` of the `ptime.clock.os` package on Unix in place of `mirage-clock`.

**Comment by sevenEng** [comment]
Thanks for your suggestion Daniel :+1:  I think I know how to circumvent this for now.

but I hope this could be fixed later or I could submit a patch for this issue, doing the conversion on the C side is a good solution imho

**Comment by dinosaure** [comment]
On my server ARMv7l, I have the same problem. A solution should be to use `Ptime_clock.*` in `mirage-clock` ?

NOTE: this is what I have:

![bug](https://snag.gy/j2ADJr.jpg)

**Comment by dinosaure** [comment]
From what I understand in mirage/mirage#442, a solution could be to use bindings provided by ptime instead of have our own implementation (which is close to what ptime does). I'm clearly not an expert about this part of the Mirage project so I need some advises of what we really need and fix this serious bug. By implementation, we will depend on `ptime` but `CLOCK` stills agnostic to `ptime` (I believe).

**Comment by hannesm** [comment]
I agree that mirage-clock-unix should just use ptime, but the `clock_stubs.c` provided by mirage-clock-unix have additional support for compiling on windows (ptime.os doesn't seem to support windows) - this was merged some time ago by @samoht and may be used in docker for windows.

**Comment by samoht** [comment]
Yes I confirm, the windows bits used to be used by Docker for Windows so it would be great to keep them. Apart from that, using ptime for the unix bindings makes sense.

**Comment by mattgray** [comment]
Hello - I think I have a fix for this in #37 - this should at least solve @dinosaure 's immediate issues running on ARMv7. I think an overall better solution would be to just use `Ptime_clock` in mirage-clock-unix, but we'd either need to add support for Windows to `ptime.os` or retain the `clock_stubs.c` in `mirage-clock-unix` just for the Windows implementation. I can have a go at doing this, but I'm not sure what the best way to approach it is.
