### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by dsheets** [mirage/mirage-clock#5]
Licences are so important for computers to manipulate that we need to yell about it.

**Comment by dbuenzli** [comment]
INDEED, but the license is already specified in the sources so I have the feeling that what is missing is rather an `opam` file with a proper `license:` field and maybe a note about the license in the `README`.

**Comment by dsheets** [comment]
All of those things would be excellent. A `LICENSE` or `LICENSE.md` would also be cool.

**Comment by djs55** [comment]
This might be a little off-topic but it would be nice if there was an easy way to extract copyright (and authorship, homepage etc?) info, so that it's possible to give credit when distributing a binary which links or otherwise composes a set of libraries. Perhaps it should be an output of the build system, alongside the binaries?

**Comment by dbuenzli** [comment]
I'm not sure the build system should fiddle with that. With enough discipline from the packagers this could be automated from `opam` files.

**Comment by avsm** [comment]
we could just include a `tag` for `license-file` perhaps?
